# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo update npm...
      - npm update -g npm
      - echo node -v
      - node -v
      - echo npm -v
      - npm -v
      - echo install yarn...
      - npm install -g yarn
      - echo yarn -v
      - yarn -v
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - printf '{"REST_EP":"%s","REST_EP_4":"%s","TOKEN":"%s","TOKEN_4":"%s"}' $REST_EP $REST_EP_4 $TOKEN $TOKEN_4 > ./dist/apps/imdb-react/rolling.json
      - echo ls
      - echo Build completed on `date`
      - if [ -z $CODEBUILD_BUILD_SUCCEDING ]; then echo "Successfully built"; fi

      # copy the contents of /dist to S3
      - aws s3 cp --recursive --acl public-read ./dist/apps/imdb-react $S3_BUCKET
      # set the cache-control headers for index.html to prevent
      # browser caching
      - >
        aws s3 cp --acl public-read 
        --cache-control="max-age=0, no-cache, no-store, must-revalidate" 
        ./dist/apps/imdb-react/index.html $S3_BUCKET
      - >
artifacts:
  files:
    - "**/*"
